# Generated by Django 4.1.1 on 2023-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='avez_vous_travaille',
            field=models.CharField(max_length=100),
        ),
    ]
