# Generated by Django 4.2.2 on 2023-08-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistory',
            name='category',
            field=models.CharField(choices=[('assign', 'Assign'), ('mention', 'Mention'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
