# Generated by Django 4.2.2 on 2023-07-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesallocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='code',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='description',
        ),
        migrations.AlterField(
            model_name='privilege',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
